// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import GameFormController from "./game_form_controller"
application.register("game-form", GameFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationSelectionController from "./location_selection_controller"
application.register("location-selection", LocationSelectionController)

import OfflineAlertController from "./offline_alert_controller"
application.register("offline-alert", OfflineAlertController)

import ServiceWorkerController from "./service_worker_controller"
application.register("service-worker", ServiceWorkerController)

import TurnTimerController from "./turn_timer_controller"
application.register("turn-timer", TurnTimerController)
