// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GameFormController from "./game_form_controller"
application.register("game-form", GameFormController)

import HandController from "./hand_controller"
application.register("hand", HandController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationSelectionController from "./location_selection_controller"
application.register("location-selection", LocationSelectionController)

import OfflineAlertController from "./offline_alert_controller"
application.register("offline-alert", OfflineAlertController)

import RummyTurnController from "./rummy_turn_controller"
application.register("rummy-turn", RummyTurnController)

import ServiceWorkerController from "./service_worker_controller"
application.register("service-worker", ServiceWorkerController)

import TurnTimerController from "./turn_timer_controller"
application.register("turn-timer", TurnTimerController)
